import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { loadModules } from "@/modules/loader"
import { getModules } from "@/modules/registry"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Sharkweb App",
  description: "Generated by sharkweb create app",
};

function applyProviders(children: React.ReactNode) {
  const modules = getModules()

  return modules.reduce((acc, m) => {
    if (!m.providers) return acc

    return m.providers.reduce((inner, Provider) => {
      return <Provider>{inner}</Provider>
    }, acc)
  }, children)
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  loadModules()

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{applyProviders(children)}</body>
    </html>
  );
}
