<<<<<<< HEAD

// Code generated by Sharkweb. DO NOT EDIT.


=======
// Code generated by Sharkweb. DO NOT EDIT.

>>>>>>> fee70ff1e1e2bf3f39b2d32d73791bcbfbd6aba9
package modules

import (
	"log"

	"github.com/gin-gonic/gin"


	"github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/core/module"

	crm "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/crm"
	health "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/health"
<<<<<<< HEAD
	inventory "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/inventory"
	Project_Management "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/Project_Management"
	

=======
	sales "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/sales"
>>>>>>> fee70ff1e1e2bf3f39b2d32d73791bcbfbd6aba9
)

func LoadModules() []module.Module {

	return []module.Module{

		crm.NewModule(),
<<<<<<< HEAD

		Project_Management.NewModule(),
		health.NewModule(),
		inventory.NewModule(),
=======
		health.NewModule(),
		sales.NewModule(),
>>>>>>> fee70ff1e1e2bf3f39b2d32d73791bcbfbd6aba9
	}
}

// func RegisterModuless(r *gin.Engine, ctx *module.ModuleContext) {

// 	api := r.Group("/api")

// 	for _, m := range LoadModules() {

// 		log.Println("🔌 Loading module:", m.Name())

// 		if err := m.Init(ctx); err != nil {
// 			log.Fatalf("❌ Failed to init module %s: %v", m.Name(), err)
// 		}

// 		group := api.Group("/" + m.Name())

// 		m.RegisterRoutes(group)

// 	}
// }

func RegisterModules(r *gin.Engine, ctx *module.ModuleContext) {

	for _, m := range LoadModules() {

<<<<<<< HEAD
		log.Println("🔌 Loading module: - modules.gen.go:24", m.Name())
=======
		log.Println("Loading module:", m.Name())
>>>>>>> fee70ff1e1e2bf3f39b2d32d73791bcbfbd6aba9

		if err := m.Init(ctx); err != nil {
			log.Fatalf("Failed to init module %s: %v", m.Name(), err)
		}

<<<<<<< HEAD
		group := api.Group("/" + m.Name())
		m.RegisterRoutes(group)
=======
		m.RegisterRoutes(&r.RouterGroup)
>>>>>>> fee70ff1e1e2bf3f39b2d32d73791bcbfbd6aba9
	}
}

// func RegisterModules(r *gin.Engine, ctx *module.ModuleContext) {

// 	api := r.Group("/api")

// 	for _, m := range LoadModules() {

// 		log.Println("🔌 Loading module:", m.Name())

// 		if err := m.Init(ctx); err != nil {
// 			log.Fatalf("❌ Failed to init module %s: %v", m.Name(), err)
// 		}

// 		group := api.Group("/" + m.Name())
// 		m.RegisterRoutes(group)
// 	}
// }